import { cn } from '@/lib/utils';
import { Inter } from 'next/font/google';
import { Toaster } from '@/components/ui/toaster';
import { FC, ReactNode } from 'react';
import Provider from '@/components/provider';
import type { Metadata } from 'next';

import '@/styles/globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: ReactNode;
}

const RootLayout: FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body className={cn(inter.className, '"min-h-screen antialiased relative')}>
        <Provider session={undefined}>
          {children}
          <Toaster />
        </Provider>
      </body>
    </html>
  );
};

export default RootLayout;
